export const INCREMENT_PID = 'INCREMENT_PID';

export const CREATE_TAB = 'CREATE_TAB';
export const CLOSE_TAB = 'CLOSE_TAB';
export const CLICK_TAB = 'CLICK_TAB';

export const DID_START_LOADING = 'DID_START_LOADING';
export const DOM_READY = 'DOM_READY';
export const DID_STOP_LOADING = 'DID_STOP_LOADING';
export const DID_FAIL_LOAD = 'DID_FAIL_LOAD';
export const PAGE_TITLE_SET = 'PAGE_TITLE_SET';
export const UPDATE_TARGET_URL = 'UPDATE_TARGET_URL';
export const MEDIA_STARTED_PLAYING = 'MEDIA_STARTED_PLAYING';
export const MEDIA_PAUSED = 'MEDIA_PAUSED';
export const TOGGLE_AUDIO = 'TOGGLE_AUDIO';
export const PAGE_FAVICON_UPDATED = 'PAGE_FAVICON_UPDATED';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const SET_CURRENT_SEARCH_ENGINE_PROVIDER = 'SET_CURRENT_SEARCH_ENGINE_PROVIDER';
export const SET_HOMEPAGE = 'SET_HOMEPAGE';
export const SET_TAB_CONFIG = 'SET_TAB_CONFIG';
export const CREATE_DOWNLOAD_TASK = 'CREATE_DOWNLOAD_TASK';
export const UPDATE_DOWNLOADS_PROGRESS = 'UPDATE_DOWNLOADS_PROGRESS';
