export const INCREMENT_TAB_ID = 'INCREMENT_TAB_ID';

export const CREATE_TAB = 'CREATE_TAB';
export const CLOSE_TAB = 'CLOSE_TAB';
export const CLOSE_ALL_TABS = 'CLOSE_ALL_TABS';
export const CLICK_TAB = 'CLICK_TAB';

export const SET_BROWSER_VIEW_ID = 'SET_BROWSER_VIEW_ID';
export const DID_START_LOADING = 'DID_START_LOADING';
export const DID_NAVIGATE = 'DID_NAVIGATE';
export const PAGE_TITLE_UPDATED = 'PAGE_TITLE_UPDATED';
export const DOM_READY = 'DOM_READY';
export const DID_FRAME_FINISH_LOAD = 'DID_FRAME_FINISH_LOAD';
export const PAGE_FAVICON_UPDATED = 'PAGE_FAVICON_UPDATED';
export const DID_STOP_LOADING = 'DID_STOP_LOADING';
export const DID_FAIL_LOAD = 'DID_FAIL_LOAD';
export const UPDATE_TARGET_URL = 'UPDATE_TARGET_URL';
export const MEDIA_STARTED_PLAYING = 'MEDIA_STARTED_PLAYING';
export const MEDIA_PAUSED = 'MEDIA_PAUSED';
export const TOGGLE_AUDIO = 'TOGGLE_AUDIO';
export const UPDATE_CERTIFICATE = 'UPDATE_CERTIFICATE';
export const UPDATE_EXTENSION_METADATA = 'UPDATE_EXTENSION_METADATA';

export const SET_CURRENT_SEARCH_ENGINE_PROVIDER = 'SET_CURRENT_SEARCH_ENGINE_PROVIDER';
export const SET_HOMEPAGE = 'SET_HOMEPAGE';
export const SET_PDF_VIEWER = 'SET_PDF_VIEWER';
export const SET_TAB_CONFIG = 'SET_TAB_CONFIG';
export const SET_LANG = 'SET_LANG';
export const SET_PROXY_CONFIG = 'SET_PROXY_CONFIG';
export const SET_AUTH = 'SET_AUTH';
export const SET_DOWNLOADS = 'SET_DOWNLOADS';
export const SET_HISTORY = 'SET_HISTORY';
export const SET_TABS_ORDER = 'SET_TABS_ORDER';
export const SET_PAGE_ACTION = 'SET_PAGE_ACTION';
export const CLEAR_PAGE_ACTION = 'CLEAR_PAGE_ACTION';
export const CREATE_DOWNLOAD_TASK = 'CREATE_DOWNLOAD_TASK';
export const UPDATE_DOWNLOADS_PROGRESS = 'UPDATE_DOWNLOADS_PROGRESS';
export const COMPLETE_DOWNLOADS_PROGRESS = 'COMPLETE_DOWNLOADS_PROGRESS';
export const CLOSE_DOWNLOAD_BAR = 'CLOSE_DOWNLOAD_BAR';

export const SET_PERMISSIONS = 'SET_PERMISSIONS';

export const UPDATE_MAPPINGS = 'UPDATE_MAPPINGS';

export const SET_LULUMI_STATE = 'SET_LULUMI_STATE';

export const CREATE_WINDOW = 'CREATE_WINDOW';
export const CLOSE_WINDOW = 'CLOSE_WINDOW';
export const UPDATE_WINDOW_PROPERTY = 'UPDATE_WINDOW_PROPERTY';

export const ADD_EXTENSION = 'ADD_EXTENSION';
export const REMOVE_EXTENSION = 'REMOVE_EXTENSION';
export const UPDATE_EXTENSION = 'UPDATE_EXTENSION';
